export declare interface Post{
    slug?: string,
    title?: string,
    description?: string,
    publishTime?: number,
    lastUpdatedTime?: number,
    tags?: string[],
    category?: string,
    plainContent?: string,
    mdContent?: string,
    summary?: string,
    wordCount?: number,
    bannerImg?: string,
    cachedHtml?: string,
    coverFit?: string,
    context?: string,
}